/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pool_table.gltf --transform 
Files: pool_table.gltf [2.94MB] > pool_table-transformed.glb [615.26KB] (79%)
Author: MH (https://sketchfab.com/MH...)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pool-table-353ac8a56c6b427592666eb01dfec65b
Title: Pool table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Pool_table(props) {
  const { nodes, materials } = useGLTF("/pool_table-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes._Joined_Solid_Geometry_4734_black_0.geometry}
        material={materials.black}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Joined_Solid_Geometry_4761_plastic2_0.geometry}
        material={materials.plastic2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Joined_Solid_Geometry_4772_green_fabric_0.geometry}
        material={materials.green_fabric}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Extrusion_4796__0.geometry}
        material={materials.Extrusion_4796__0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Revolve_4840_red_0.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Revolve_4864_yellow_0.geometry}
        material={materials.yellow}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Joined_Solid_Geometry_4976_aluminum_0.geometry}
        material={materials.aluminum}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes._Blend_15419_wood_0.geometry}
        material={materials.wood}
        position={[0, 0.011, -1.279]}
        rotation={[-Math.PI / 2, 0, -2.471]}
        scale={0.21}
      />
    </group>
  );
}
